services:
  consul:
    image: hashicorp/consul:1.16.2
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - pro_microservice-network
    volumes:
      - ./consul/config:/consul/config
      - ./consul/certs:/consul/certs
    command: "agent -dev -client=0.0.0.0 -config-dir=/consul/config"

networks:
  pro_microservice-network:
    external: true
